apiVersion: vpcv1.ibmcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: harry-subnet-cidr-1
  annotations:
spec:
  deletionPolicy: Delete
  forProvider:
    byCIDR:
      ipv4CIDRBlock: 10.240.64.0/24
      vpc: 
        vpcRef: 
          name: harry-vpc-2-meta-name
      resourceGroup:
        id: b706e89f4ddc4a90b59a383409673135    
  providerConfigRef:
    name: ibm-cloud