apiVersion: vpcv1.ibmcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: harry-vpc-3
  annotations:
spec:
  deletionPolicy: Orphan
  forProvider:
    classicAccess: false
    name: harry-vpc-3
    headers:
        key_uno: value_uno
        key_due: value_due 
  providerConfigRef:
    name: ibm-cloud
