apiVersion: container.containerv2.ibmcloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: meta-harry-crossplane-made-1
  annotations:
spec:
  deletionPolicy: Delete
  forProvider:
    name: harry-crossplane-made-1
    disablePublicServiceEndpoint: true
    provider: vpc-gen2
    kubeVersion: 1.21.7_1541
    podSubnet: 172.17.0.0/18
    serviceSubnet: 172.21.0.0/16
    cosInstanceCRN: 'crn:v1:bluemix:public:cloud-object-storage:global:a/4916c9cb6f87d36886c13a43cb4e7786:5ffc919d-1366-4396-b624-bc577a412664::'
    defaultWorkerPoolEntitlement: ''
    workerPool:
      name: my-worker-pool
      entitlement: ''
      flavor: cx2.2x4
      vpcRef: 
        name: harry-vpc-2-meta-name
      workerCount: 2
      zones:
        - id: us-south-1
          subnetID: 0727-9b298420-022d-40a8-bb28-143d4c9e94c1
  providerConfigRef:
    name: ibm-cloud
