apiVersion: container.containerv2.ibmcloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: metadata-name-1
  annotations:
spec:
  deletionPolicy: Delete
  forProvider:
    name: crossplane-1
    disablePublicServiceEndpoint: true
    provider: vpc-gen2
    kubeVersion: 1.21.7_1541
    podSubnet: 172.17.0.0/18
    serviceSubnet: 172.21.0.0/16
    cosInstanceCRN: 'crn:v1:bluemix:public:containers-kubernetes:us-south:a/0b5a00334eaf9eb9339d2ab48f20d7f5:c7jkited0fh21rkqk92g::'
    defaultWorkerPoolEntitlement: ''
    workerPool:
      name: my-worker-pool
      entitlement: ''
      flavor: cx2.2x4
      vpcID: r006-58c15986-7fdd-4a69-a4ee-211f50b14668
      workerCount: 2
      zones:
        - id: us-south-1
          subnetID: 0717-2af44258-e749-481a-868e-a7cc167464d0
  providerConfigRef:
    name: ibm-cloud
