//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/crossplane/crossplane-runtime/apis/core/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingCPUGroupCPU) DeepCopyInto(out *AutoscalingCPUGroupCPU) {
	*out = *in
	if in.Scalers != nil {
		in, out := &in.Scalers, &out.Scalers
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(AutoscalingCPUGroupCPURate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingCPUGroupCPU.
func (in *AutoscalingCPUGroupCPU) DeepCopy() *AutoscalingCPUGroupCPU {
	if in == nil {
		return nil
	}
	out := new(AutoscalingCPUGroupCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingCPUGroupCPURate) DeepCopyInto(out *AutoscalingCPUGroupCPURate) {
	*out = *in
	if in.IncreasePercent != nil {
		in, out := &in.IncreasePercent, &out.IncreasePercent
		*out = new(int64)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.LimitCountPerMember != nil {
		in, out := &in.LimitCountPerMember, &out.LimitCountPerMember
		*out = new(int64)
		**out = **in
	}
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingCPUGroupCPURate.
func (in *AutoscalingCPUGroupCPURate) DeepCopy() *AutoscalingCPUGroupCPURate {
	if in == nil {
		return nil
	}
	out := new(AutoscalingCPUGroupCPURate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingDiskGroupDisk) DeepCopyInto(out *AutoscalingDiskGroupDisk) {
	*out = *in
	if in.Scalers != nil {
		in, out := &in.Scalers, &out.Scalers
		*out = new(AutoscalingDiskGroupDiskScalers)
		(*in).DeepCopyInto(*out)
	}
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(AutoscalingDiskGroupDiskRate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingDiskGroupDisk.
func (in *AutoscalingDiskGroupDisk) DeepCopy() *AutoscalingDiskGroupDisk {
	if in == nil {
		return nil
	}
	out := new(AutoscalingDiskGroupDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingDiskGroupDiskRate) DeepCopyInto(out *AutoscalingDiskGroupDiskRate) {
	*out = *in
	if in.IncreasePercent != nil {
		in, out := &in.IncreasePercent, &out.IncreasePercent
		*out = new(int64)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.LimitMbPerMember != nil {
		in, out := &in.LimitMbPerMember, &out.LimitMbPerMember
		*out = new(int64)
		**out = **in
	}
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingDiskGroupDiskRate.
func (in *AutoscalingDiskGroupDiskRate) DeepCopy() *AutoscalingDiskGroupDiskRate {
	if in == nil {
		return nil
	}
	out := new(AutoscalingDiskGroupDiskRate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingDiskGroupDiskScalers) DeepCopyInto(out *AutoscalingDiskGroupDiskScalers) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(AutoscalingDiskGroupDiskScalersCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.IoUtilization != nil {
		in, out := &in.IoUtilization, &out.IoUtilization
		*out = new(AutoscalingDiskGroupDiskScalersIoUtilization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingDiskGroupDiskScalers.
func (in *AutoscalingDiskGroupDiskScalers) DeepCopy() *AutoscalingDiskGroupDiskScalers {
	if in == nil {
		return nil
	}
	out := new(AutoscalingDiskGroupDiskScalers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingDiskGroupDiskScalersCapacity) DeepCopyInto(out *AutoscalingDiskGroupDiskScalersCapacity) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FreeSpaceLessThanPercent != nil {
		in, out := &in.FreeSpaceLessThanPercent, &out.FreeSpaceLessThanPercent
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingDiskGroupDiskScalersCapacity.
func (in *AutoscalingDiskGroupDiskScalersCapacity) DeepCopy() *AutoscalingDiskGroupDiskScalersCapacity {
	if in == nil {
		return nil
	}
	out := new(AutoscalingDiskGroupDiskScalersCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingDiskGroupDiskScalersIoUtilization) DeepCopyInto(out *AutoscalingDiskGroupDiskScalersIoUtilization) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverPeriod != nil {
		in, out := &in.OverPeriod, &out.OverPeriod
		*out = new(string)
		**out = **in
	}
	if in.AbovePercent != nil {
		in, out := &in.AbovePercent, &out.AbovePercent
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingDiskGroupDiskScalersIoUtilization.
func (in *AutoscalingDiskGroupDiskScalersIoUtilization) DeepCopy() *AutoscalingDiskGroupDiskScalersIoUtilization {
	if in == nil {
		return nil
	}
	out := new(AutoscalingDiskGroupDiskScalersIoUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingGroup) DeepCopyInto(out *AutoscalingGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingGroup.
func (in *AutoscalingGroup) DeepCopy() *AutoscalingGroup {
	if in == nil {
		return nil
	}
	out := new(AutoscalingGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingGroupList) DeepCopyInto(out *AutoscalingGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoscalingGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingGroupList.
func (in *AutoscalingGroupList) DeepCopy() *AutoscalingGroupList {
	if in == nil {
		return nil
	}
	out := new(AutoscalingGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingGroupObservation) DeepCopyInto(out *AutoscalingGroupObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingGroupObservation.
func (in *AutoscalingGroupObservation) DeepCopy() *AutoscalingGroupObservation {
	if in == nil {
		return nil
	}
	out := new(AutoscalingGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingGroupParameters) DeepCopyInto(out *AutoscalingGroupParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IDRef != nil {
		in, out := &in.IDRef, &out.IDRef
		*out = new(corev1alpha1.Reference)
		**out = **in
	}
	if in.IDSelector != nil {
		in, out := &in.IDSelector, &out.IDSelector
		*out = new(corev1alpha1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(AutoscalingDiskGroupDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(AutoscalingMemoryGroupMemory)
		(*in).DeepCopyInto(*out)
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(AutoscalingCPUGroupCPU)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingGroupParameters.
func (in *AutoscalingGroupParameters) DeepCopy() *AutoscalingGroupParameters {
	if in == nil {
		return nil
	}
	out := new(AutoscalingGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingGroupSpec) DeepCopyInto(out *AutoscalingGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.ConnectionTemplates != nil {
		in, out := &in.ConnectionTemplates, &out.ConnectionTemplates
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingGroupSpec.
func (in *AutoscalingGroupSpec) DeepCopy() *AutoscalingGroupSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingGroupStatus) DeepCopyInto(out *AutoscalingGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingGroupStatus.
func (in *AutoscalingGroupStatus) DeepCopy() *AutoscalingGroupStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingMemoryGroupMemory) DeepCopyInto(out *AutoscalingMemoryGroupMemory) {
	*out = *in
	if in.Scalers != nil {
		in, out := &in.Scalers, &out.Scalers
		*out = new(AutoscalingMemoryGroupMemoryScalers)
		(*in).DeepCopyInto(*out)
	}
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(AutoscalingMemoryGroupMemoryRate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingMemoryGroupMemory.
func (in *AutoscalingMemoryGroupMemory) DeepCopy() *AutoscalingMemoryGroupMemory {
	if in == nil {
		return nil
	}
	out := new(AutoscalingMemoryGroupMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingMemoryGroupMemoryRate) DeepCopyInto(out *AutoscalingMemoryGroupMemoryRate) {
	*out = *in
	if in.IncreasePercent != nil {
		in, out := &in.IncreasePercent, &out.IncreasePercent
		*out = new(int64)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.LimitMbPerMember != nil {
		in, out := &in.LimitMbPerMember, &out.LimitMbPerMember
		*out = new(int64)
		**out = **in
	}
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingMemoryGroupMemoryRate.
func (in *AutoscalingMemoryGroupMemoryRate) DeepCopy() *AutoscalingMemoryGroupMemoryRate {
	if in == nil {
		return nil
	}
	out := new(AutoscalingMemoryGroupMemoryRate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingMemoryGroupMemoryScalers) DeepCopyInto(out *AutoscalingMemoryGroupMemoryScalers) {
	*out = *in
	if in.IoUtilization != nil {
		in, out := &in.IoUtilization, &out.IoUtilization
		*out = new(AutoscalingMemoryGroupMemoryScalersIoUtilization)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingMemoryGroupMemoryScalers.
func (in *AutoscalingMemoryGroupMemoryScalers) DeepCopy() *AutoscalingMemoryGroupMemoryScalers {
	if in == nil {
		return nil
	}
	out := new(AutoscalingMemoryGroupMemoryScalers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingMemoryGroupMemoryScalersIoUtilization) DeepCopyInto(out *AutoscalingMemoryGroupMemoryScalersIoUtilization) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OverPeriod != nil {
		in, out := &in.OverPeriod, &out.OverPeriod
		*out = new(string)
		**out = **in
	}
	if in.AbovePercent != nil {
		in, out := &in.AbovePercent, &out.AbovePercent
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingMemoryGroupMemoryScalersIoUtilization.
func (in *AutoscalingMemoryGroupMemoryScalersIoUtilization) DeepCopy() *AutoscalingMemoryGroupMemoryScalersIoUtilization {
	if in == nil {
		return nil
	}
	out := new(AutoscalingMemoryGroupMemoryScalersIoUtilization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	in.Members.DeepCopyInto(&out.Members)
	in.Memory.DeepCopyInto(&out.Memory)
	in.CPU.DeepCopyInto(&out.CPU)
	in.Disk.DeepCopyInto(&out.Disk)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupCPU) DeepCopyInto(out *GroupCPU) {
	*out = *in
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
	if in.MinimumCount != nil {
		in, out := &in.MinimumCount, &out.MinimumCount
		*out = new(int64)
		**out = **in
	}
	if in.MaximumCount != nil {
		in, out := &in.MaximumCount, &out.MaximumCount
		*out = new(int64)
		**out = **in
	}
	if in.StepSizeCount != nil {
		in, out := &in.StepSizeCount, &out.StepSizeCount
		*out = new(int64)
		**out = **in
	}
	if in.IsAdjustable != nil {
		in, out := &in.IsAdjustable, &out.IsAdjustable
		*out = new(bool)
		**out = **in
	}
	if in.IsOptional != nil {
		in, out := &in.IsOptional, &out.IsOptional
		*out = new(bool)
		**out = **in
	}
	if in.CanScaleDown != nil {
		in, out := &in.CanScaleDown, &out.CanScaleDown
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupCPU.
func (in *GroupCPU) DeepCopy() *GroupCPU {
	if in == nil {
		return nil
	}
	out := new(GroupCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupDisk) DeepCopyInto(out *GroupDisk) {
	*out = *in
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
	if in.MinimumMb != nil {
		in, out := &in.MinimumMb, &out.MinimumMb
		*out = new(int64)
		**out = **in
	}
	if in.MaximumMb != nil {
		in, out := &in.MaximumMb, &out.MaximumMb
		*out = new(int64)
		**out = **in
	}
	if in.StepSizeMb != nil {
		in, out := &in.StepSizeMb, &out.StepSizeMb
		*out = new(int64)
		**out = **in
	}
	if in.IsAdjustable != nil {
		in, out := &in.IsAdjustable, &out.IsAdjustable
		*out = new(bool)
		**out = **in
	}
	if in.IsOptional != nil {
		in, out := &in.IsOptional, &out.IsOptional
		*out = new(bool)
		**out = **in
	}
	if in.CanScaleDown != nil {
		in, out := &in.CanScaleDown, &out.CanScaleDown
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupDisk.
func (in *GroupDisk) DeepCopy() *GroupDisk {
	if in == nil {
		return nil
	}
	out := new(GroupDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupMembers) DeepCopyInto(out *GroupMembers) {
	*out = *in
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
	if in.MinimumCount != nil {
		in, out := &in.MinimumCount, &out.MinimumCount
		*out = new(int64)
		**out = **in
	}
	if in.MaximumCount != nil {
		in, out := &in.MaximumCount, &out.MaximumCount
		*out = new(int64)
		**out = **in
	}
	if in.StepSizeCount != nil {
		in, out := &in.StepSizeCount, &out.StepSizeCount
		*out = new(int64)
		**out = **in
	}
	if in.IsAdjustable != nil {
		in, out := &in.IsAdjustable, &out.IsAdjustable
		*out = new(bool)
		**out = **in
	}
	if in.IsOptional != nil {
		in, out := &in.IsOptional, &out.IsOptional
		*out = new(bool)
		**out = **in
	}
	if in.CanScaleDown != nil {
		in, out := &in.CanScaleDown, &out.CanScaleDown
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupMembers.
func (in *GroupMembers) DeepCopy() *GroupMembers {
	if in == nil {
		return nil
	}
	out := new(GroupMembers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupMemory) DeepCopyInto(out *GroupMemory) {
	*out = *in
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = new(string)
		**out = **in
	}
	if in.MinimumMb != nil {
		in, out := &in.MinimumMb, &out.MinimumMb
		*out = new(int64)
		**out = **in
	}
	if in.MaximumMb != nil {
		in, out := &in.MaximumMb, &out.MaximumMb
		*out = new(int64)
		**out = **in
	}
	if in.StepSizeMb != nil {
		in, out := &in.StepSizeMb, &out.StepSizeMb
		*out = new(int64)
		**out = **in
	}
	if in.IsAdjustable != nil {
		in, out := &in.IsAdjustable, &out.IsAdjustable
		*out = new(bool)
		**out = **in
	}
	if in.IsOptional != nil {
		in, out := &in.IsOptional, &out.IsOptional
		*out = new(bool)
		**out = **in
	}
	if in.CanScaleDown != nil {
		in, out := &in.CanScaleDown, &out.CanScaleDown
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupMemory.
func (in *GroupMemory) DeepCopy() *GroupMemory {
	if in == nil {
		return nil
	}
	out := new(GroupMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingGroup) DeepCopyInto(out *ScalingGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingGroup.
func (in *ScalingGroup) DeepCopy() *ScalingGroup {
	if in == nil {
		return nil
	}
	out := new(ScalingGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingGroupList) DeepCopyInto(out *ScalingGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScalingGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingGroupList.
func (in *ScalingGroupList) DeepCopy() *ScalingGroupList {
	if in == nil {
		return nil
	}
	out := new(ScalingGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScalingGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingGroupObservation) DeepCopyInto(out *ScalingGroupObservation) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingGroupObservation.
func (in *ScalingGroupObservation) DeepCopy() *ScalingGroupObservation {
	if in == nil {
		return nil
	}
	out := new(ScalingGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingGroupParameters) DeepCopyInto(out *ScalingGroupParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IDRef != nil {
		in, out := &in.IDRef, &out.IDRef
		*out = new(corev1alpha1.Reference)
		**out = **in
	}
	if in.IDSelector != nil {
		in, out := &in.IDSelector, &out.IDSelector
		*out = new(corev1alpha1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = new(SetMembersGroupMembers)
		**out = **in
	}
	if in.MemberMemory != nil {
		in, out := &in.MemberMemory, &out.MemberMemory
		*out = new(SetMemoryGroupMemory)
		**out = **in
	}
	if in.MemberCPU != nil {
		in, out := &in.MemberCPU, &out.MemberCPU
		*out = new(SetCPUGroupCPU)
		**out = **in
	}
	if in.MemberDisk != nil {
		in, out := &in.MemberDisk, &out.MemberDisk
		*out = new(SetDiskGroupDisk)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingGroupParameters.
func (in *ScalingGroupParameters) DeepCopy() *ScalingGroupParameters {
	if in == nil {
		return nil
	}
	out := new(ScalingGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingGroupSpec) DeepCopyInto(out *ScalingGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.ConnectionTemplates != nil {
		in, out := &in.ConnectionTemplates, &out.ConnectionTemplates
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingGroupSpec.
func (in *ScalingGroupSpec) DeepCopy() *ScalingGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingGroupStatus) DeepCopyInto(out *ScalingGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingGroupStatus.
func (in *ScalingGroupStatus) DeepCopy() *ScalingGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ScalingGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetCPUGroupCPU) DeepCopyInto(out *SetCPUGroupCPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetCPUGroupCPU.
func (in *SetCPUGroupCPU) DeepCopy() *SetCPUGroupCPU {
	if in == nil {
		return nil
	}
	out := new(SetCPUGroupCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetDiskGroupDisk) DeepCopyInto(out *SetDiskGroupDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetDiskGroupDisk.
func (in *SetDiskGroupDisk) DeepCopy() *SetDiskGroupDisk {
	if in == nil {
		return nil
	}
	out := new(SetDiskGroupDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetMembersGroupMembers) DeepCopyInto(out *SetMembersGroupMembers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetMembersGroupMembers.
func (in *SetMembersGroupMembers) DeepCopy() *SetMembersGroupMembers {
	if in == nil {
		return nil
	}
	out := new(SetMembersGroupMembers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetMemoryGroupMemory) DeepCopyInto(out *SetMemoryGroupMemory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetMemoryGroupMemory.
func (in *SetMemoryGroupMemory) DeepCopy() *SetMemoryGroupMemory {
	if in == nil {
		return nil
	}
	out := new(SetMemoryGroupMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Whitelist) DeepCopyInto(out *Whitelist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Whitelist.
func (in *Whitelist) DeepCopy() *Whitelist {
	if in == nil {
		return nil
	}
	out := new(Whitelist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Whitelist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistEntry) DeepCopyInto(out *WhitelistEntry) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistEntry.
func (in *WhitelistEntry) DeepCopy() *WhitelistEntry {
	if in == nil {
		return nil
	}
	out := new(WhitelistEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistList) DeepCopyInto(out *WhitelistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Whitelist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistList.
func (in *WhitelistList) DeepCopy() *WhitelistList {
	if in == nil {
		return nil
	}
	out := new(WhitelistList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WhitelistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistObservation) DeepCopyInto(out *WhitelistObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistObservation.
func (in *WhitelistObservation) DeepCopy() *WhitelistObservation {
	if in == nil {
		return nil
	}
	out := new(WhitelistObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistParameters) DeepCopyInto(out *WhitelistParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IDRef != nil {
		in, out := &in.IDRef, &out.IDRef
		*out = new(corev1alpha1.Reference)
		**out = **in
	}
	if in.IDSelector != nil {
		in, out := &in.IDSelector, &out.IDSelector
		*out = new(corev1alpha1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]WhitelistEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IfMatch != nil {
		in, out := &in.IfMatch, &out.IfMatch
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistParameters.
func (in *WhitelistParameters) DeepCopy() *WhitelistParameters {
	if in == nil {
		return nil
	}
	out := new(WhitelistParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistSpec) DeepCopyInto(out *WhitelistSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.ConnectionTemplates != nil {
		in, out := &in.ConnectionTemplates, &out.ConnectionTemplates
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistSpec.
func (in *WhitelistSpec) DeepCopy() *WhitelistSpec {
	if in == nil {
		return nil
	}
	out := new(WhitelistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistStatus) DeepCopyInto(out *WhitelistStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistStatus.
func (in *WhitelistStatus) DeepCopy() *WhitelistStatus {
	if in == nil {
		return nil
	}
	out := new(WhitelistStatus)
	in.DeepCopyInto(out)
	return out
}
