apiVersion: vpcv1.ibmcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: harry-vpc-2-meta-name
  annotations:
spec:
  deletionPolicy: Delete
  forProvider:
    classicAccess: false
    name: harry-vpc-2
    resourceGroup:
      id: b706e89f4ddc4a90b59a383409673135
  providerConfigRef:
    name: ibm-cloud
